version: "3.2"

services:
  db:
    image: mysql
    volumes:
      - 'mysql:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: jsteven
      MYSQL_PASSWORD: jsteven

  app_db:
    build: ./app-db
    depends_on:
      - db
    links:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: test      
      DB_USER: jsteven
      DB_PASS: jsteven

  app_api:
    build: ./app-api
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/src/app'

volumes:
  mysql:
